language: node_js
node_js:
  - "12"
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  fqdn: visualizer.jamielau.me
  on:
    branch: master

dist: bionic
sudo: false
